name: Codex Bridge
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  handle:
    if: >
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '@codex') ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@codex'))
    runs-on: self-hosted
    steps:
      - name: Ensure jq present (self-hosted)
        run: |
          command -v jq >/dev/null || (echo "jq missing on runner" && exit 1)
      - uses: actions/checkout@v4
      - name: Allow only owner
        run: |
          WHO="${{ github.event.comment.user.login || github.event.issue.user.login }}"
          ALLOWED="rossgalloway"
          if [ "$WHO" != "$ALLOWED" ]; then
            echo "Not allowed: $WHO"
            printf '{"body":"⛔ Not allowed for user %s."}\n' "$WHO" > result.json
            exit 0
          fi
      - name: Parse command
        id: parse
        run: |
          python3 .github/scripts/parse_and_dispatch.py \
            --event "$GITHUB_EVENT_PATH" \
            --repo "$GITHUB_REPOSITORY" \
            --issue "${{ github.event.issue.number || github.event.comment.issue_url##*/ }}" \
            > cmd.json
      - name: Run Codex command (Inspector path)
        id: codex
        run: |
          python3 .github/scripts/run_codex.py cmd.json > result.json || echo "{}" > result.json
      - name: Post reply (always)
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body=$(jq -r '.body // "Codex ran with no output."' result.json 2>/dev/null || echo "workflow failed without body")
          gh issue comment ${{ github.event.issue.number || github.event.comment.issue_url##*/ }} --body "$body"
