name: Codex Bridge
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  handle:
    if: >
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '@codex') ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@codex'))
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Parse command
        id: parse
        run: |
          python3 .github/scripts/parse_and_dispatch.py \
            --event "$GITHUB_EVENT_PATH" \
            --repo "$GITHUB_REPOSITORY" \
            --issue "${{ github.event.issue.number || github.event.comment.issue_url##*/ }}" \
            > cmd.json
      - name: Run Codex command
        id: codex
        run: |
          python3 .github/scripts/run_codex.py cmd.json > result.json || echo "{}" > result.json
      - name: Post reply
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          body=$(jq -r '.body // "Codex ran with no output."' result.json)
          gh issue comment ${{ github.event.issue.number || github.event.comment.issue_url##*/ }} --body "$body"
